In [1]:
import numpy as np

In [2]:
zeros_array = np.zeros(10)

In [3]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [4]:
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)

In [6]:
my_list

[2, 3, 4]

In [7]:
array_from_list

array([2, 3, 4])

In [8]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.full((5, 2), 3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [10]:
arr = np.array([[2, 3, 4], [4, 5, 6]])

In [11]:
arr

array([[2, 3, 4],
       [4, 5, 6]])

In [12]:
arr[0,1]

np.int64(3)

In [13]:
arr[0,1]=20

In [14]:
arr

array([[ 2, 20,  4],
       [ 4,  5,  6]])

In [15]:
arr[0]

array([ 2, 20,  4])

In [16]:
arr[:,0]

array([2, 4])

In [17]:
import pandas as pd

pd.__version__

'2.3.1'

Getting the data
For this homework, we'll use the Car Fuel Efficiency dataset. Download it from here.


In [18]:
df = pd.read_csv("car_fuel_efficiency.txt")
df.head()


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

Q2. Records count
How many records are in the dataset?

4704
8704
9704
17704

In [19]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

Q3. Fuel types
How many fuel types are presented in the dataset?

1
2
3
4

In [20]:
df.nunique()

engine_displacement      36
num_cylinders            14
horsepower              192
vehicle_weight         9704
acceleration            162
model_year               24
origin                    3
fuel_type                 2
drivetrain                2
num_doors                 9
fuel_efficiency_mpg    9704
dtype: int64

Q4. Missing values
How many columns in the dataset have missing values?

0
1
2
3
4

In [21]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [22]:
Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

13.75
23.75
33.75
43.75

SyntaxError: unterminated string literal (detected at line 2) (1616195381.py, line 2)

In [ ]:
df[df["origin"]=='Asia']["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

Q6. Median value of horsepower
1. Find the median value of horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No

In [ ]:
h_median = df["horsepower"].median()
print(h_median)

h_mode = df["horsepower"].mode()
print(h_mode)

df["horsepower"].fillna(h_mode)

df["horsepower"].median()

149.0
0    152.0
Name: horsepower, dtype: float64


np.float64(149.0)

Q7. Sum of weights
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

0.051
0.51
5.1
51

In [32]:
df_asia = df[df["origin"]=="Asia"]

df_asia = df_asia[["vehicle_weight", "model_year"]]

df_asia





vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [36]:
X = df_asia.iloc[[0,1,2,3,4,5,6]].values

X
#type(X)

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [37]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result


def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result


def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [38]:
XTX = matrix_matrix_multiplication(X.T, X)
XTX

array([[62248334.33150762, 41431216.50732678],
       [41431216.50732678, 28373339.        ]])

In [39]:
invXTX = np.linalg.inv(XTX)
invXTX

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [40]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
type(y)

numpy.ndarray

In [41]:
w = matrix_vector_multiplication(
        matrix_matrix_multiplication(invXTX, X.T), 
        y
)
w


array([0.01386421, 0.5049067 ])

In [42]:
sum(w)

np.float64(0.5187709081074002)