In [4]:
import numpy as np

In [6]:
zeros_array = np.zeros(10)

In [7]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [8]:
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
my_list = [2, 3, 4]
array_from_list = np.array(my_list)

In [10]:
my_list

[2, 3, 4]

In [11]:
array_from_list

array([2, 3, 4])

In [12]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.full((5, 2), 3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [14]:
arr = np.array([[2, 3, 4], [4, 5, 6]])

In [15]:
arr

array([[2, 3, 4],
       [4, 5, 6]])

In [16]:
arr[0,1]

np.int64(3)

In [17]:
arr[0,1]=20

In [18]:
arr

array([[ 2, 20,  4],
       [ 4,  5,  6]])

In [19]:
arr[0]

array([ 2, 20,  4])

In [20]:
arr[:,0]

array([2, 4])